### ISSUE TITLE
Repeated crashing soon after track recognition

### ISSUE THREAD

**Issue by DrTexx** [sekaru/spotify-lifx-visualiser#10]
## Brief overview
This occurs a large percentage of the time. I have gotten the light bulbs to work about 3 times in a row after disabling my firewall, however they've stopped working again since with this same issue.

## Computer information
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
```
$ npm -v
5.8.0
```

## Output from error
```
[...]
New track: Reaching Out by Bassnectar
/home/denver/github/spotify-lifx-visualiser/services/lights.js:214
    beatTimer.clearTimeout();
              ^

TypeError: Cannot read property 'clearTimeout' of undefined
    at updateBeatNum (/home/denver/github/spotify-lifx-visualiser/services/lights.js:214:15)
    at /home/denver/github/spotify-lifx-visualiser/services/lights.js:203:9
    at Request._callback (/home/denver/github/spotify-lifx-visualiser/services/spotify.js:28:20)
    at Request.self.callback (/home/denver/github/spotify-lifx-visualiser/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/home/denver/github/spotify-lifx-visualiser/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/home/denver/github/spotify-lifx-visualiser/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[nodemon] app crashed - waiting for file changes before starting...
```

Please let me know if you need any further information or if I've missed something obvious, I would love to check this out finally working and would love to also potentially contribute in future.

**Comment by tudddorrr** [comment]
Hey there, I just pushed a possible fix if you want to pull down. Let me know if that works.
