### ISSUE TITLE
app crashing immediately

### ISSUE THREAD

**Issue by oscardobsonbrown** [sekaru/spotify-lifx-visualiser#16]
When I start the program with `node app.js --beatmode 1 --colourmode 2 --lights`
it gives me this error
`
> lifx-visualiser@1.0.0 start C:\Users\user\spotify-lifx-visualiser
> nodemon app.js "--beatmode" "1" "--colourmode" "2" "--lights"

[nodemon] 1.18.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js --beatmode 1 --colourmode 2 --lights`
C:\Users\user\spotify-lifx-visualiser\services\lights.js:18
const LIGHTS_TO_USE = argv.l ? argv.l.toLowerCase().split(', ') : argv.lights ? argv.lights.toLowerCase().split(', ') : [];
                                                                                            ^

TypeError: argv.lights.toLowerCase is not a function
    at Object.<anonymous> (C:\Users\user\spotify-lifx-visualiser\services\lights.js:18:93)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\user\spotify-lifx-visualiser\app.js:11:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by oscardobsonbrown** [comment]
I think I fixed it. I left the --lights arg which wasn't meant to be there
