### ISSUE TITLE
Crash upon starting track

### ISSUE THREAD

**Issue by NotActuallyTerry** [sekaru/spotify-lifx-visualiser#2]
Hi, whenever I try to play a track I get this error  
```
/home/build/spotify-lifx-visualiser/services/lights.js:80
  for(var i=0; i<audioAnalysis.segments.length; i++) {
                                        ^

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.initBeat (/home/build/spotify-lifx-visualiser/services/lights.js:80:41)
    at Request._callback (/home/build/spotify-lifx-visualiser/services/spotify.js:46:18)
    at Request.self.callback (/home/build/spotify-lifx-visualiser/node_modules/request/request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/build/spotify-lifx-visualiser/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/build/spotify-lifx-visualiser/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
My settings are ``-b 2 -c 2``

**Comment by NotActuallyTerry** [comment]
To add onto this, it also occurs just after logging in, before I start playing any track

**Comment by tudddorrr** [comment]
You've gone through the setup process creating your own Spotify app and creating the .env file right? Without looking too closely into it I assume it's because the API call is failing because you're not properly authenticated.

**Comment by NotActuallyTerry** [comment]
Yeah, I've gone through all of those steps, and it authenticates me properly, showing which track I'm playing and all

**Comment by tudddorrr** [comment]
Strange. What OS are you using?

**Comment by NotActuallyTerry** [comment]
I was using an ArchLinux system to host the script, and I authed/listened to the track on a Windows machine within the same network

**Comment by tudddorrr** [comment]
Alright sorry for the slow reply. Currently in the process of moving so I'll try and get the bulbs setup and have an answer for you ASAP.

**Comment by tudddorrr** [comment]
Sorry this has taken so long. Put in a little bandaid in the latest commit, let me know if that sorts it out for you.

**Comment by jessicah** [comment]
I'm also seeing this :( After a few restarts, it will start working. I wonder if Spotify doesn't have analysis immediately? I'm currently using the backup branch, as having problems with master, but master branch also ran into similar issues (although the lights didn't seem to want to play along...)

**Comment by tudddorrr** [comment]
Fixed with https://github.com/sekaru/spotify-lifx-visualiser/commit/01216e14733d55f3be8179149b5244d50176e050
