### ISSUE TITLE
Crashes soon after detecting song

### ISSUE THREAD

**Issue by jarr0** [sekaru/spotify-lifx-visualiser#8]
Hi, as soon as it detects the song play I keep getting this error

```
/Path/To/spotify-lifx-visualiser/services/lights.js:214
  for(var i=0; i<audioAnalysis.segments.length; i++) {
                               ^

TypeError: Cannot read property 'segments' of undefined
    at updateBeatNum (/Users/jarrodross/spotify-lifx-visualiser/services/lights.js:214:32)
    at /Users/jarrodross/spotify-lifx-visualiser/services/lights.js:203:9
    at Request._callback (/Users/jarrodross/spotify-lifx-visualiser/services/spotify.js:28:20)
    at Request.self.callback (/Users/jarrodross/spotify-lifx-visualiser/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (/Users/jarrodross/spotify-lifx-visualiser/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (/Users/jarrodross/spotify-lifx-visualiser/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)

```

The only thing I had to do different was when I was running `npm install` it would crash shortly after so I then deleted the package-lock.json file and nodes_modules folder and ran the command again and it install with no issue. 

Runnig macOS 10.14

**Comment by tudddorrr** [comment]
Seems like sometimes Spotify doesn't return you the audio analysis. Will try and fix this weekend.

**Comment by tudddorrr** [comment]
Should be fixed now, let me know
